//! Agent loop - the core think-act-observe cycle.
//!
//! This is the agent's main execution loop. It:
//! 1. Sends the conversation to the LLM
//! 2. Receives the response (text + tool calls)
//! 3. Executes tools (local or harness)
//! 4. Feeds results back to the LLM
//! 5. Repeats until the LLM stops calling tools
//!
//! The loop supports both local tools (think, remember, plan, web_search, files)
//! and harness tools (accessed via HTTP through the HarnessClient).

use crate::{
    compact::{self, CompactionConfig},
    harness_client::HarnessClient,
    provider::ModelProvider,
    tools::{self, ToolContext},
};
use amos_core::{
    hooks::{self, HookConfig, HookEvent},
    permissions::{self, PermissionPolicy},
    types::{ContentBlock, Message, Role},
    Result,
};
use chrono::Utc;
use serde::{Deserialize, Serialize};
use tracing::{debug, info, warn};

/// Configuration for the agent loop.
#[derive(Debug, Clone)]
pub struct LoopConfig {
    pub max_iterations: usize,
    pub system_prompt: String,
    pub model_id: String,
    /// Hook configuration for pre/post tool execution.
    pub hooks: HookConfig,
    /// Permission policy for this session.
    pub permissions: PermissionPolicy,
    /// Auto-compaction configuration.
    pub compaction: CompactionConfig,
}

impl Default for LoopConfig {
    fn default() -> Self {
        Self {
            max_iterations: 25,
            system_prompt: default_system_prompt(),
            model_id: "claude-sonnet-4-6".to_string(),
            hooks: HookConfig::default(),
            permissions: PermissionPolicy::default(),
            compaction: CompactionConfig::default(),
        }
    }
}

/// Events emitted during agent execution for external consumers.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum AgentEvent {
    TurnStart {
        iteration: usize,
    },
    #[serde(rename = "message_delta")]
    TextDelta {
        content: String,
    },
    ToolStart {
        tool_name: String,
        is_local: bool,
        /// Summary of tool input for progress display (e.g. collection name, page title)
        #[serde(skip_serializing_if = "Option::is_none")]
        input_summary: Option<String>,
    },
    ToolEnd {
        tool_name: String,
        duration_ms: u64,
        is_error: bool,
        /// Brief result summary for progress display
        #[serde(skip_serializing_if = "Option::is_none")]
        result_summary: Option<String>,
        /// Optional metadata from the tool (e.g. canvas actions, site preview info)
        #[serde(skip_serializing_if = "Option::is_none")]
        metadata: Option<serde_json::Value>,
    },
    TurnEnd {
        iteration: usize,
        tokens_used: u64,
    },
    #[serde(rename = "agent_end")]
    Done {
        total_iterations: usize,
        total_tokens: u64,
        total_input_tokens: u64,
        total_output_tokens: u64,
        model_id: String,
        final_text: String,
    },
    /// Streaming tool input as it's being generated by the LLM.
    ToolInputDelta {
        tool_name: String,
        partial_input: String,
    },
    /// Conversation was auto-compacted to stay within token budget.
    Compacted {
        removed_messages: usize,
        estimated_tokens: usize,
    },
    /// A hook denied tool execution.
    HookDenied {
        tool_name: String,
        hook_message: String,
    },
    Error {
        message: String,
    },
}

/// Run the agent loop to completion.
#[allow(clippy::too_many_arguments)]
pub async fn run_agent_loop(
    config: &LoopConfig,
    provider: &dyn ModelProvider,
    tool_ctx: &ToolContext,
    harness: Option<&HarnessClient>,
    initial_message: &str,
    content_blocks: Option<Vec<ContentBlock>>,
    history: Option<Vec<Message>>,
    workspace_context: Option<serde_json::Value>,
    event_tx: Option<tokio::sync::mpsc::Sender<AgentEvent>>,
) -> Result<String> {
    let mut messages: Vec<Message> = Vec::new();

    // Build tool schemas: local tools + harness tools
    let local_defs = tools::local_tool_definitions();
    let mut all_tool_schemas = tools::tool_definitions_to_json(&local_defs);
    let local_tool_names: Vec<String> = local_defs.iter().map(|d| d.name.clone()).collect();

    if let Some(h) = harness {
        all_tool_schemas.extend(h.harness_tool_schemas());
    }

    // Build the effective system prompt, injecting workspace context if provided
    let system_prompt = if let Some(ref ws_ctx) = workspace_context {
        let ctx_str = serde_json::to_string_pretty(ws_ctx).unwrap_or_default();
        format!(
            "{}\n\n## Current Workspace Context\n\n```json\n{}\n```",
            config.system_prompt, ctx_str
        )
    } else {
        config.system_prompt.clone()
    };

    // Prepend conversation history if resuming a session
    if let Some(hist) = history {
        let windowed = window_history(hist, 40);
        messages.extend(windowed);
        info!(
            history_messages = messages.len(),
            "Loaded conversation history"
        );
    }

    // Add the initial user message.
    // If content blocks are provided (from attachments), build a multi-block
    // message with the text first, followed by images/documents.
    let initial_content = if let Some(mut blocks) = content_blocks {
        // Prepend the user's text message
        blocks.insert(
            0,
            ContentBlock::Text {
                text: initial_message.to_string(),
            },
        );
        blocks
    } else {
        vec![ContentBlock::Text {
            text: initial_message.to_string(),
        }]
    };

    messages.push(Message {
        role: Role::User,
        content: initial_content,
        tool_use_id: None,
        timestamp: Utc::now(),
    });

    // Auto-recall: search local memory for context relevant to the user's message
    // before the first LLM call. This gives the agent background knowledge from
    // prior conversations without requiring it to call a tool.
    {
        let mem_store = tool_ctx.memory.lock().await;
        if let Ok(memories) = mem_store.search(initial_message, 5) {
            if !memories.is_empty() {
                let memory_text = memories
                    .iter()
                    .map(|m| format!("- {}: {}", m.key, m.content))
                    .collect::<Vec<_>>()
                    .join("\n");
                // Insert before the current user message
                let insert_pos = messages.len().saturating_sub(1);
                messages.insert(
                    insert_pos,
                    Message {
                        role: Role::User,
                        content: vec![ContentBlock::Text {
                            text: format!(
                                "[Relevant memories from past conversations:\n{}]",
                                memory_text
                            ),
                        }],
                        tool_use_id: None,
                        timestamp: Utc::now(),
                    },
                );
                debug!(count = memories.len(), "Auto-recalled memories for context");
            }
        }
    }

    let mut total_tokens: u64 = 0;
    let mut total_input_tokens: u64 = 0;
    let mut total_output_tokens: u64 = 0;
    let mut final_text = String::new();

    for iteration in 0..config.max_iterations {
        // Auto-compact if approaching token limit
        if let Some(result) = compact::maybe_compact(&messages, &config.compaction) {
            info!(
                removed = result.removed_count,
                tokens = result.estimated_tokens,
                "Auto-compacted conversation"
            );
            emit(
                &event_tx,
                AgentEvent::Compacted {
                    removed_messages: result.removed_count,
                    estimated_tokens: result.estimated_tokens,
                },
            )
            .await;
            messages = result.messages;
        }

        emit(&event_tx, AgentEvent::TurnStart { iteration }).await;
        debug!(iteration, "Agent loop iteration");

        // Call the model with retry-on-rate-limit.
        // Anthropic (and other providers) return 429 when the rate limit is
        // exceeded.  We retry up to 3 times with exponential backoff (5s, 15s, 30s)
        // so transient rate-limit hits don't immediately kill the conversation.
        let (response, usage) = {
            let backoffs = [5u64, 15, 30]; // seconds
            let mut attempt = 0;

            loop {
                match provider
                    .converse(
                        &config.model_id,
                        &system_prompt,
                        &messages,
                        &all_tool_schemas,
                    )
                    .await
                {
                    Ok(result) => break result,
                    Err(e) => {
                        let err_str = format!("{e}");
                        let is_rate_limit = err_str.contains("429")
                            || err_str.contains("rate_limit")
                            || err_str.contains("Too Many Requests");

                        if is_rate_limit && attempt < backoffs.len() {
                            let wait = backoffs[attempt];
                            tracing::warn!(
                                attempt = attempt + 1,
                                wait_secs = wait,
                                "Rate-limited by provider, backing off"
                            );
                            emit(
                                &event_tx,
                                AgentEvent::Error {
                                    message: format!(
                                        "Rate-limited — waiting {wait}s before retry ({}/3)...",
                                        attempt + 1
                                    ),
                                },
                            )
                            .await;
                            tokio::time::sleep(std::time::Duration::from_secs(wait)).await;
                            attempt += 1;
                            continue;
                        }

                        let error_msg = format!("LLM provider error: {e}");
                        tracing::error!("{}", error_msg);
                        emit(
                            &event_tx,
                            AgentEvent::Error {
                                message: error_msg.clone(),
                            },
                        )
                        .await;
                        return Err(e);
                    }
                }
            }
        };

        total_tokens += usage.total_tokens;
        total_input_tokens += usage.input_tokens;
        total_output_tokens += usage.output_tokens;

        // Extract text content and tool calls from the response
        let mut has_tool_calls = false;
        let mut response_text = String::new();
        let mut tool_calls: Vec<(String, String, serde_json::Value)> = Vec::new();

        for block in &response.content {
            match block {
                ContentBlock::Text { text } => {
                    response_text.push_str(text);
                    emit(
                        &event_tx,
                        AgentEvent::TextDelta {
                            content: text.clone(),
                        },
                    )
                    .await;
                }
                ContentBlock::ToolUse { id, name, input } => {
                    has_tool_calls = true;
                    tool_calls.push((id.clone(), name.clone(), input.clone()));
                }
                _ => {}
            }
        }

        if !response_text.is_empty() {
            final_text = response_text.clone();
        }

        // Add assistant message to conversation
        messages.push(response);

        emit(
            &event_tx,
            AgentEvent::TurnEnd {
                iteration,
                tokens_used: usage.total_tokens,
            },
        )
        .await;

        // If no tool calls, the agent is done
        if !has_tool_calls {
            info!(iteration, "Agent loop completed (no more tool calls)");
            break;
        }

        // Execute tool calls and collect results
        let mut tool_results: Vec<ContentBlock> = Vec::new();

        for (tool_id, tool_name, input) in &tool_calls {
            let is_local = local_tool_names.contains(tool_name);
            let input_summary = summarize_tool_input(tool_name, input);

            // Permission check
            let required_perm = permissions::default_tool_permission(tool_name);
            if !config.permissions.allows_tool(tool_name, required_perm) {
                let msg = format!(
                    "Permission denied: '{}' requires {:?} but session is {:?}",
                    tool_name, required_perm, config.permissions.active_mode
                );
                warn!("{}", msg);
                tool_results.push(ContentBlock::ToolResult {
                    tool_use_id: tool_id.clone(),
                    content: msg,
                    is_error: true,
                });
                continue;
            }

            // Pre-tool hook
            let hook_result = hooks::run_hooks(
                &config.hooks,
                HookEvent::PreToolUse,
                tool_name,
                input,
                None,
                None,
            )
            .await;
            if hook_result.denied {
                let msg = hook_result
                    .messages
                    .first()
                    .cloned()
                    .unwrap_or_else(|| format!("Hook denied execution of '{tool_name}'"));
                emit(
                    &event_tx,
                    AgentEvent::HookDenied {
                        tool_name: tool_name.clone(),
                        hook_message: msg.clone(),
                    },
                )
                .await;
                tool_results.push(ContentBlock::ToolResult {
                    tool_use_id: tool_id.clone(),
                    content: format!("Blocked by hook: {msg}"),
                    is_error: true,
                });
                continue;
            }

            emit(
                &event_tx,
                AgentEvent::ToolStart {
                    tool_name: tool_name.clone(),
                    is_local,
                    input_summary,
                },
            )
            .await;

            let start = std::time::Instant::now();

            let (result_content, is_error, tool_metadata) = if is_local {
                // Execute locally
                match tools::execute_local_tool(tool_name, input, tool_ctx).await {
                    Ok(content) => (content, false, None),
                    Err(e) => (format!("Tool error: {e}"), true, None),
                }
            } else if let Some(harness_name) = tool_name.strip_prefix("harness_") {
                // Execute on the harness
                if let Some(h) = harness {
                    match h.execute_tool(harness_name, input.clone(), None).await {
                        Ok(resp) => (resp.content, resp.is_error, resp.metadata),
                        Err(e) => {
                            // Suppress errors for workspace summary — it's non-critical
                            // context loading that should not surface to the user.
                            if harness_name == "get_workspace_summary" {
                                tracing::warn!("Workspace summary unavailable: {e}");
                                (
                                    r#"{"note":"Workspace context not available"}"#.to_string(),
                                    false,
                                    None,
                                )
                            } else {
                                (format!("Harness tool error: {e}"), true, None)
                            }
                        }
                    }
                } else {
                    (
                        format!("Harness not connected - cannot execute {tool_name}"),
                        true,
                        None,
                    )
                }
            } else {
                (format!("Unknown tool: {tool_name}"), true, None)
            };

            let duration_ms = start.elapsed().as_millis() as u64;
            let result_summary = summarize_tool_result(tool_name, &result_content, is_error);

            // Post-tool hook (fire and forget — doesn't affect result)
            let _post_hook = hooks::run_hooks(
                &config.hooks,
                HookEvent::PostToolUse,
                tool_name,
                input,
                Some(&result_content),
                Some(is_error),
            )
            .await;

            emit(
                &event_tx,
                AgentEvent::ToolEnd {
                    tool_name: tool_name.clone(),
                    duration_ms,
                    is_error,
                    result_summary,
                    metadata: tool_metadata,
                },
            )
            .await;

            tool_results.push(ContentBlock::ToolResult {
                tool_use_id: tool_id.clone(),
                content: truncate_tool_result(&result_content),
                is_error,
            });
        }

        // Add tool results as a user message (matching the Bedrock/Anthropic pattern)
        messages.push(Message {
            role: Role::User,
            content: tool_results,
            tool_use_id: None,
            timestamp: Utc::now(),
        });
    }

    emit(
        &event_tx,
        AgentEvent::Done {
            total_iterations: messages.len() / 2,
            total_tokens,
            total_input_tokens,
            total_output_tokens,
            model_id: config.model_id.clone(),
            final_text: final_text.clone(),
        },
    )
    .await;

    Ok(final_text)
}

/// Truncate tool result content to prevent context window overflow.
/// Web search and other tools can return very large results that balloon
/// the conversation past the LLM's token limit.
const MAX_TOOL_RESULT_CHARS: usize = 15_000;

fn truncate_tool_result(content: &str) -> String {
    if content.len() <= MAX_TOOL_RESULT_CHARS {
        content.to_string()
    } else {
        let truncated = &content[..MAX_TOOL_RESULT_CHARS];
        format!(
            "{truncated}\n\n[... truncated — result was {} chars, limit is {}]",
            content.len(),
            MAX_TOOL_RESULT_CHARS
        )
    }
}

async fn emit(tx: &Option<tokio::sync::mpsc::Sender<AgentEvent>>, event: AgentEvent) {
    if let Some(tx) = tx {
        let _ = tx.send(event).await;
    }
}

/// Extract a human-readable summary from tool input for progress display.
fn summarize_tool_input(tool_name: &str, input: &serde_json::Value) -> Option<String> {
    // Strip the harness_ prefix for matching
    let base_name = tool_name.strip_prefix("harness_").unwrap_or(tool_name);

    match base_name {
        "define_collection" => {
            let name = input.get("name").and_then(|v| v.as_str())?;
            let field_count = input
                .get("fields")
                .and_then(|v| v.as_array())
                .map(|a| a.len())
                .unwrap_or(0);
            Some(format!("Defining '{}' ({} fields)", name, field_count))
        }
        "create_record" => {
            let coll = input.get("collection").and_then(|v| v.as_str())?;
            Some(format!("Creating record in '{}'", coll))
        }
        "update_record" => {
            let id = input
                .get("record_id")
                .and_then(|v| v.as_str())
                .unwrap_or("...");
            Some(format!("Updating record {}", &id[..8.min(id.len())]))
        }
        "query_records" | "list_records" => {
            let coll = input.get("collection").and_then(|v| v.as_str())?;
            Some(format!("Querying '{}'", coll))
        }
        "create_canvas" => {
            let title = input.get("title").and_then(|v| v.as_str())?;
            Some(format!("Creating canvas '{}'", title))
        }
        "update_canvas" => {
            let title = input
                .get("title")
                .and_then(|v| v.as_str())
                .unwrap_or("canvas");
            Some(format!("Updating canvas '{}'", title))
        }
        "create_site" => {
            let name = input.get("name").and_then(|v| v.as_str()).unwrap_or("site");
            Some(format!("Creating site '{}'", name))
        }
        "create_page" => {
            let title = input
                .get("title")
                .and_then(|v| v.as_str())
                .unwrap_or("page");
            Some(format!("Building page '{}'", title))
        }
        "publish_site" => Some("Publishing site".to_string()),
        "create_automation" => {
            let name = input
                .get("name")
                .and_then(|v| v.as_str())
                .unwrap_or("automation");
            Some(format!("Creating automation '{}'", name))
        }
        "ingest_document" => {
            let title = input
                .get("title")
                .and_then(|v| v.as_str())
                .unwrap_or("document");
            Some(format!("Ingesting '{}'", title))
        }
        "search_knowledge" | "semantic_search" => {
            let q = input.get("query").and_then(|v| v.as_str())?;
            let truncated = if q.len() > 50 { &q[..50] } else { q };
            Some(format!("Searching: {}", truncated))
        }
        "web_search" => {
            let q = input.get("query").and_then(|v| v.as_str())?;
            let truncated = if q.len() > 50 { &q[..50] } else { q };
            Some(format!("Searching web: {}", truncated))
        }
        "create_app" => {
            let name = input.get("name").and_then(|v| v.as_str()).unwrap_or("app");
            let view_count = input
                .get("views")
                .and_then(|v| v.as_array())
                .map(|a| a.len())
                .unwrap_or(0);
            Some(format!("Creating app '{}' ({} views)", name, view_count))
        }
        "update_app_view" => {
            let view = input
                .get("view_slug")
                .and_then(|v| v.as_str())
                .unwrap_or("view");
            Some(format!("Updating app view '{}'", view))
        }
        "get_workspace_summary" => Some("Loading workspace context".to_string()),
        "delete_record" => Some("Deleting record".to_string()),
        "delete_collection" => {
            let name = input.get("name").and_then(|v| v.as_str())?;
            Some(format!("Deleting collection '{}'", name))
        }
        _ => None,
    }
}

/// Extract a brief summary from tool result for progress display.
fn summarize_tool_result(tool_name: &str, result: &str, is_error: bool) -> Option<String> {
    if is_error {
        // Truncate error message for display
        let msg = if result.len() > 100 {
            format!("{}...", &result[..100])
        } else {
            result.to_string()
        };
        return Some(format!("Error: {}", msg));
    }

    let base_name = tool_name.strip_prefix("harness_").unwrap_or(tool_name);

    // Try to parse as JSON for structured results
    if let Ok(json) = serde_json::from_str::<serde_json::Value>(result) {
        match base_name {
            "define_collection" => {
                let name = json.get("name").and_then(|v| v.as_str())?;
                Some(format!("Collection '{}' ready", name))
            }
            "create_record" => {
                let id = json.get("id").and_then(|v| v.as_str()).unwrap_or("ok");
                Some(format!("Record created ({})", &id[..8.min(id.len())]))
            }
            "create_app" => {
                let name = json.get("name").and_then(|v| v.as_str())?;
                let views = json.get("view_count").and_then(|v| v.as_u64()).unwrap_or(0);
                Some(format!("App '{}' created ({} views)", name, views))
            }
            "update_app_view" => {
                let view = json.get("view_slug").and_then(|v| v.as_str())?;
                let action = json
                    .get("action")
                    .and_then(|v| v.as_str())
                    .unwrap_or("updated");
                Some(format!("View '{}' {}", view, action))
            }
            "create_site" => {
                let slug = json.get("slug").and_then(|v| v.as_str())?;
                Some(format!("Site created at /s/{}", slug))
            }
            "create_page" => {
                let title = json.get("title").and_then(|v| v.as_str())?;
                Some(format!("Page '{}' created", title))
            }
            "publish_site" => Some("Site published".to_string()),
            "query_records" | "list_records" => {
                let count = json.get("total").and_then(|v| v.as_u64())?;
                Some(format!("{} records found", count))
            }
            _ => None,
        }
    } else {
        None
    }
}

/// Window conversation history to prevent context overflow.
///
/// Keeps the first `keep_start` messages (topic establishment) and the last
/// `keep_end` messages (recent context). Middle messages are summarized as a
/// brief text note so the agent knows topics were discussed.
fn window_history(messages: Vec<Message>, max_messages: usize) -> Vec<Message> {
    if messages.len() <= max_messages {
        return messages;
    }

    let keep_start = 2usize;
    let keep_end = 20usize;

    let first_end = keep_start.min(messages.len());
    let last_start = messages.len().saturating_sub(keep_end);
    // Ensure we don't overlap
    let last_start = last_start.max(first_end);

    let first = &messages[..first_end];
    let middle = &messages[first_end..last_start];
    let last = &messages[last_start..];

    let mut windowed: Vec<Message> = first.to_vec();

    if !middle.is_empty() {
        // Extract text snippets from the middle to form a brief summary
        let snippets: Vec<&str> = middle
            .iter()
            .filter(|m| m.role == Role::User || m.role == Role::Assistant)
            .filter_map(|m| {
                m.content.iter().find_map(|b| match b {
                    ContentBlock::Text { text } => {
                        let trimmed = text.trim();
                        if trimmed.is_empty() {
                            None
                        } else if trimmed.len() > 80 {
                            Some(&trimmed[..80])
                        } else {
                            Some(trimmed)
                        }
                    }
                    _ => None,
                })
            })
            .take(10)
            .collect();

        let summary_text = if snippets.is_empty() {
            format!("[{} earlier messages omitted]", middle.len())
        } else {
            format!(
                "[{} earlier messages omitted. Topics: {}]",
                middle.len(),
                snippets.join(" | ")
            )
        };

        windowed.push(Message {
            role: Role::User,
            content: vec![ContentBlock::Text { text: summary_text }],
            tool_use_id: None,
            timestamp: Utc::now(),
        });
    }

    windowed.extend_from_slice(last);
    windowed
}

fn default_system_prompt() -> String {
    r#"You are AMOS Agent, an autonomous AI assistant that is part of the AMOS ecosystem.

You have access to local tools (think, remember, recall, plan, web_search, read_file, write_file) that run directly on your machine, and harness tools (prefixed with harness_) that execute on the AMOS Harness server.

Guidelines:
1. Workspace context is provided automatically at the start of each new conversation. For follow-up questions, conversation history is included automatically. Use "harness_get_workspace_summary" only if you need to refresh workspace state mid-conversation.
2. Use the "think" tool to reason through complex problems before acting.
3. Use "remember" to store important facts and "recall" to retrieve them.
4. Use "plan" to break complex tasks into steps.
5. Use file tools when you need to read or create files.
6. Harness tools (harness_*) are for database operations, document processing, and other platform capabilities.

Knowledge base — persistent memory across sessions:
- "harness_knowledge_search" performs semantic search over all ingested documents and memories. Use it when the user asks about previously shared information, uploaded documents, or business context.
- "harness_ingest_document" stores a document permanently in the knowledge base with embeddings for future search. Use it when the user provides important reference material.
- Documents uploaded as attachments are automatically ingested into the knowledge base in the background.

Web search — two-stage pattern (IMPORTANT):
- "web_search" returns lightweight snippets only. Use it to find relevant URLs.
- "harness_view_web_page" fetches full page content. Use it selectively on the 1-2 most relevant URLs from search results.
- Do NOT call web_search repeatedly with similar queries. Review results before searching again.
- Do NOT call harness_view_web_page on every search result — pick only the most promising URLs.

Building apps vs websites:
- For interactive applications (CRMs, dashboards, project trackers, admin panels), use "harness_create_app" to create a multi-view app backed by collections. Specify views with component types (data_table, kanban, dashboard, form, chart). The AMOS component library handles data fetching, rendering, and interactivity automatically.
- For static websites (landing pages, marketing sites, portfolios), use "harness_create_site" and "harness_create_page" with raw HTML/CSS/JS.
- Always create the underlying collections/schema first, then build the app views on top of them.

Specialist assistants — extending your capabilities:
- Use "harness_list_available_specialists" to see what specialist types can be activated.
- When users need capabilities you don't have (research, education), offer to activate a specialist.
- Use "harness_activate_specialist" to bring one online. Say "I'm setting up a Research Assistant" — never "provisioning a harness."
- Once active, use "harness_delegate_to_harness" to send work to specialists. Present results as your own — the user doesn't need to know about delegation.
- Use "harness_list_harnesses" to check what's running. Present as "your active specialists."
- NEVER say "harness," "container," "Docker," "provisioning," or "package" to users. Use "specialist," "assistant," or "capability."

Bounty execution — when executing bounties from the AMOS relay:
- Bounties are tasks posted to the AMOS marketplace. When assigned a bounty, treat it as a focused work assignment.
- Break the task into clear steps using the plan tool before starting.
- Use code execution and file tools to produce concrete, testable artifacts.
- Test your work before considering it complete.
- Structure your final output clearly:
  - **APPROACH**: Your strategy for solving the task
  - **IMPLEMENTATION**: What you built and key decisions
  - **VERIFICATION**: How you tested and verified correctness
  - **ARTIFACTS**: Files created or modified
- Self-evaluate against the task requirements. If your output is incomplete, continue working.
- Quality matters: bounty approval depends on complete, well-structured deliverables.

Always be helpful, accurate, and thorough. If unsure, search the web or think through the problem first."#
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_config() {
        let config = LoopConfig::default();
        assert_eq!(config.max_iterations, 25);
        assert!(config.system_prompt.contains("AMOS Agent"));
    }

    #[test]
    fn test_default_system_prompt_contents() {
        let prompt = default_system_prompt();
        assert!(prompt.contains("think"));
        assert!(prompt.contains("remember"));
        assert!(prompt.contains("web_search"));
        assert!(prompt.contains("harness_"));
    }
}
